- name: Install apt https transport
  apt:
    name: [ca-certificates, apt-transport-https]
    state: latest

- name: Set up additional repos
  template:
    dest: '/etc/apt/sources.list.d/{{ item }}'
    src: '{{ item }}.j2'
  with_items:
    - mongodb.list
    - unifi_network.list

- name: Add missing GPG keys from Ubuntu.com
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ item }}'
    state: present
  with_items:
    - 06E85760C0A52C50   # Unifi
    - 58712A2291FA4AD5   # MongoDB

# - name: Add mongodb gpg key
#   apt_key:
#     keyserver: https://www.mongodb.org/static/pgp/server-3.6.asc
#     id: 58712A2291FA4AD5

#     state: present
#     dest: 

# - name: Ensure we have mongodb gpg key
#   get_url:
#     url: https://www.mongodb.org/static/pgp/server-3.6.asc
#     dest: /usr/share/keyrings/mongodb.gpg

- name: Install openjdk-8
  apt:
   name: openjdk-8-jre-headless
   state: present
   update_cache: yes

- name: Ensure we are using openjdk-8 by default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    priority: 40

- name: Install Unifi Network
  apt:
    name: [unifi]
    state: latest
    install_recommends: yes
    update_cache: yes

- include: certs.yml




