- set_fact:
    bucket_id: '{{ item.bucket.split("/")[0] }}'

- name: Create excludeDirsRegex string
  set_fact: 
    excludeDirs: '{% for d in item.ignore_dirs | default([]) %} --excludeDirRegex "{{ d }}"{% endfor %}'

- name: Ensure backup job is set up.
  cron: 
    hour: '{{ item.hour | default(backblaze_default_hour) }}'
    minute: '{{ item.minute | default("00") }}'
    day: '{{ item.day | default("*") }}'
    month: '{{ item.month | default("*") }}'
    weekday: '{{ item.weekday | default("*") }}'
    name: 'Backblaze Backup for {{ item.path }} to {{ item.bucket }}'
    job: 'python3 /root/backup_summary.py {{ item.path }}'
