- name: Ensure python3-venv is installed
  apt:
    name: python3-venv
    state: present

# Pip Install
- block:
  - name: Ensure backblaze's b2 script exists
    stat: 
      path: '{{ backblaze_venv }}'
    register: backblaze_dir
    changed_when: not backblaze_dir.stat.exists | default(true)
  - name: Set up Python Virtual Environment
    command: 'python3 -m venv /{{ backblaze_venv }}'
    when: backblaze_dir.changed
  - name: Ensure b2 is installed
    pip:
      name: b2
      virtualenv: '{{ backblaze_venv }}'
      state: latest

# Deal with account registration for b2.
- include: account.yml

- include: backups.yml
  loop: '{{ backblaze_backups }}'

- name: 'Set up backup configuration.'
  template:
    src: b2.conf.j2
    dest: '{{ backblaze_config_dir }}/.b2.conf'
    mode: '0700'

- name: Ensure backup summary script exists.
  copy:
    src: backup_summary.py
    dest: /root/backup_summary.py
    mode: 0700
    