- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted
  
- name: reload monit
  service:
    name: monit
    state: reloaded