---
- hosts: dns
  tasks:
    - name: Backup DNS
      include_role:
        name: dns
        tasks_from: backups
  tags:
    - dns

- hosts: ldap
  tasks:
    - name: Backup LDAP
      include_role:
        name: ldap
        tasks_from: backups
  tags:
    - ldap

- hosts: mail
  tasks:
  - name: Backup email
    include_role:
      name: mail
      tasks_from: backups
  tags:
    - mail

- hosts: webmail
  tasks:
  - name: Backup webmail
    include_role:
      name: roundcube
      tasks_from: backups
  tags:
    - webmail
    - roundcube

- hosts: emby
  tasks:
  - name: Backup emby
    include_role:
      name: emby
      tasks_from: backups
  tags:
    - emby

- hosts: kodi
  tasks:
  - name: Backup kodi
    include_role:
      name: kodi
      tasks_from: backups
  tags:
    - kodi