---
- hosts: all
  roles: 
    - {role: common, tags: common}

- hosts: dev
  roles:
    - {role: dev, tags: dev}
    - {role: vboxguest, tags: vbosguest}

- hosts: local_dns
  roles:  
    - {role: pihole, tags: [pihole, local_dns]}

- hosts: samba
  roles:
    - samba
  tags: 
    - samba

- hosts: vboxhost
  roles:
    - virtualbox
  tags:
    - virtualbox

- hosts: dns
  roles:
    - dns
  tags:
    - dns

- hosts: emby_server
  roles:
    - emby_server
  tags:
    - emby
    - emby_server
    - emby-server
    - emby server

- hosts: emby_theater
  roles:
    - emby_theater
  tags:
    - emby_theater
    - emby-theater
    - emby theater

- hosts: dashy
  roles:
    - dashy
  tags:
    - dashy

- hosts: ldap
  roles:
    - ldap
  tags:
    - ldap

- hosts: mail
  roles:
    - mail
  tags:
    - mail
    
- hosts: webmail
  roles:
    - roundcube
  tags:
    - webmail
    - roundcube

- hosts: pbx
  roles:
    - pbx
  tags:
    - pbx

- hosts: transmission
  roles:
    - transmission
  tags:
    - transmission
    - torrents

- hosts: backblaze
  roles:
    - backblaze
  tags:
    - backblaze

- hosts: sendmail
  roles:
    - sendmail
  tags:
    - sendmail

- hosts: wiki
  roles:
    - wiki
  tags:
    - wiki

- hosts: vpn
  roles:
    - wireguard
  tags:
    - vpn
    - wireguard

- hosts: unifi_os
  roles:
    - unifi_os
  tags:
    - unifi
    - unifi os
    - unifi_os
    - unifi network
    - unifi_network
    - unifi protect
    - unifi_protect
