- hosts: all
  tasks:
    - name: Update Debian apt packages.
      block:
        - name: Update apt
          apt:
            update_cache: yes
            force_apt_get: yes
            cache_valid_time: 3600
        - name: Upgrade all packages on servers
          apt:
            upgrade: dist
            force_apt_get: yes
        - name: Remove unused packages
          apt:
            autoremove: yes
            purge: yes
        - name: Check if a reboot is needed on all servers
          register: reboot_required_file
          stat:
            path: /var/run/reboot-required
            get_md5: no
          changed_when: reboot_required_file.stat.exists
        - name: Reboot the server if kernel updated
          reboot:
            msg: "Reboot initiated by Ansible for kernel updates"
            connect_timeout: 5
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime
          when: reboot_required_file.stat.exists and allow_reboot | default(false)
      when: ansible_os_family == 'Debian' and 'unifi_os' not in group_names
