# Set env using extra-vars:
# ansible-playbook -D -i env/production/inventory.yml --extra-vars "env=production" websites.yml

- hosts: site_ip
  roles:
    - site_ip
  tags:
    - site_ip
    - ip_site

- hosts: files
  roles:
    - files
  tags:
    - files

- import_playbook: '{{ env | default("none") }}_websites.yml'

