- block:
  - name: Ensure certbot is installed
    apt:
      name:  python3-certbot-dns-rfc2136
      state: present
  - set_fact:
      certbot_bin: /usr/bin/certbot
  when: ansible_distribution == 'Debian'
  
- block:
  - name: Ensure certbot is installed
    yum:
      name:  python2-certbot-dns-rfc2136
      state: present
  - set_fact:
      certbot_bin: /usr/bin/certbot-2
  when: ansible_distribution == 'Sangoma'

- name: Ensure we have a cert group
  group:
    name: '{{ cert_group }}'
    state: present

- set_fact: 
      certbot_key_file: "{{ lookup('file', backup_dir + '/dns/certbot.key') }}"

- name: Update certbot.ini file
  template:
    dest: /root/.certbot.ini
    src: certbot.ini.j2
    mode: '0700'

- name: Check if key file exists.
  command: '/usr/bin/test -f /etc/letsencrypt/live/{{ cert_name}}/privkey.pem'
  register: cert_key
  failed_when: false
  changed_when: cert_key.rc == 1

- set_fact:
    deploy_hook: "{{ cert_services | join(';') }}"

- block:
    - name: "Run certbot for {{ cert_name }}"
      shell: "{{ certbot_bin }} certonly --dns-rfc2136 --dns-rfc2136-credentials /root/.certbot.ini --non-interactive --agree-tos --email {{ cert_email }} --cert-name {{ cert_name }} -d {{ cert_domains | join(' -d ') }}"
      register: new_cert
  when: cert_key.changed

- set_fact:
    deploy_hook_string: --deploy-hook "{{ deploy_hook }}"
  when: deploy_hook != []
- set_fact:
    deploy_hook_string: ""
  when: deploy_hook == ""

- name: Update cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: '{{ certbot_bin }} renew --quiet {{ deploy_hook_string }}'
    minute: "{{ (59 |random(seed=ansible_hostname)) }}"
    hour: "08"

- name: Ensure ssl-certs group can access the keys
  file:
    state: directory
    group: ssl-certs
    mode: 750
    path: "/etc/letsencrypt/live/{{ cert_name }}"
    recurse: yes
  changed_when: false

- name: Give group permissions to the Let's Encrypt root folder.
  file:
    path: /etc/letsencrypt/
    group: ssl-certs
    recurse: yes

- name: Set mode on Let's Encrypt Live/Archive folder.
  file:
    path: '/etc/letsencrypt/{{ item }}'
    mode: '0750'
  register: perms_update
  with_items:
    - live
    - archive
