backup_dir: "{{ playbook_dir }}/env/{{ env }}/backups"

primary_mail_domain: "{{ default_domain }}"
mail_hostname: "mail.{{ primary_mail_domain }}"
mail_domains: ['{{ primary_mail_domain }}']
mail_ipv6: "{{ ipv6_address | default(false) }}"
mail_localip: 127.0.0.3
message_size_limit: 20480000
dqs_key: false

doveadm_password: false
doveadm_port: 12345
sieve_port: 4190

ldap_scheme: ldapi
ldap_server: '%2Fvar%2Frun%2Fldapi'
ldap_tls: false
ldap_suffix: "{{ 'dc={0},dc={1}'.format(*primary_mail_domain.split('.')) }}"
ldap_admin: "cn=admin,{{ ldap_suffix }}"
#ldap_pw: ''

rspamd_hostname: "rspamd.{{ primary_mail_domain }}"
rspamd_ipv6: "{{ ipv6_address | default(false) }}"
#rspamd_controller_password: ''
rspamd_reject: 15
rspamd_add_header: 5
rspamd_rewrite_subject: 8
rspamd_greylist: 4
rspamd_list_dbs: [email_denylist.inc, domain_denylist.inc, regex_denylist.inc,
                  domain_allowlist.inc, email_allowlist.inc]

trusted_hosts: []
mail_mynetworks: []

spammed_accounts: []
rejected_addresses: {}
tld_spam_score: {'cam': 4.0, 'us': 1.0, 'club': 4.0}

dkim_key: dkim
dkim_keys: ['{{ dkim_key }}']

