backup_dir: "{{ playbook_dir }}/env/{{ env }}/backups"

ldap_domain: "{{ primary_mail_domain }}"
ldap_suffix: "{{ 'dc={0},dc={1}'.format(*ldap_domain.split('.')) }}"
ldap_admin: "cn=admin,{{ ldap_suffix }}"
# Default has LDAP on local mail host
ldap_schema: ldapi
ldap_server: '%2Fvar%2Frun%2Fldapi'
ldap_tls: false

mail_hostname: "mail.{{ primary_mail_domain }}"
mail_domains: 
  - '{{ primary_mail_domain }}'
mail_ipv6: "{{ ipv6_address | default(false) }}"
mail_localip: 127.0.0.3
mail_debug: false
message_size_limit: 20480000

tld_spam_score: {'cam': 4.0, 'us': 1.0, 'club': 4.0}
spammed_accounts: []
spam_milter: rspamd
rspamd_hostname: "rspamd.{{ primary_mail_domain }}"
rspamd_ipv6: "{{ ipv6_address | default(false) }}"
# Score actions
rspamd_reject: 15
rspamd_add_header: 5
rspamd_rewrite_subject: 8
rspamd_greylist: 4
# Multimap
rspamd_list_dbs: 
  - email_denylist.inc
  - domain_denylist.inc
  - regex_denylist.inc
  - domain_allowlist.inc
  - email_allowlist.inc

dqs_key: False
dkim_key: 'dkim'

doveadm_passwd: false
doveadm_port: 12345
doveadm_allow_list: []
sieve_port: 4190
