- name: Check if Asterisk is installed.
  stat:
    path: /var/spool/asterisk
  register: asterisk_installed
  changed_when: not asterisk_installed.stat.exists
  failed_when: false

- block:
  - name: Download Installation script from Github
    get_url: 
      url: 'https://raw.githubusercontent.com/FreePBX/sng_freepbx_debian_install/master/sng_freepbx_debian_install.sh'
      dest: /tmp/sng_freepbx_debian_install.sh
      mode: 0770

  - name: Install FreePBX
    command: bash /tmp/sng_freepbx_debian_install.sh
  when: asterisk_installed.failed

- include_tasks: certs.yml

