- name: Install samba
  apt:
    name: samba
    state: latest

- name: Install pexpect for creating samba users
  apt:
    name: python3-pexpect
    state: latest

- name: Update samba config file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba

# Deal with samba Users
- include: users.yml
  with_dict: "{{ samba_users }}"
  no_log: true  # Keep this so passwords don't show in plain text.

- include: shares.yml
  with_dict: "{{ samba_shares }}"

# Handle certs
- include: certs.yml
  tags:
    - certs

- name: Ensure samba is running
  systemd:
    state: started
    name: smbd
    enabled: yes

- name: Updated samba monit configuration
  template:
    src: monit.j2
    dest: /etc/monit/conf.d/samba
  notify: restart monit
  when: monit_enabled | default(true)