- name: Ensure GPG is installed
  apt:
    name: gpg
    state: present

- name: Ensure we have the NodeSource GPG key
  apt_key:
    keyserver: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280'
    state: present
    keyring: /usr/share/keyrings/nodesource.gpg

- name: Ensure NodeSource is in our repository.
  template:
    src: nodesource.list.j2
    dest: /etc/apt/sources.list.d/nodesource.list

- name: Ensure nodejs is installed using NodeSource repository.
  template:
    src: nodesource.pref.j2
    dest: /etc/apt/preferences.d/nodesource.pref

- name: 'Ensure nodejs {{ node_version }} is installed'
  apt:
    state: present
    update_cache: yes
    name: nodejs
