backup_dir: "{{ playbook_dir }}/env/{{ env }}/backups"

roundcube_hostname: "webmail.{{ default_domain }}"
roundcube_extra_hostnames: []
roundcube_ipv6: "{{ ipv6_address | default(false) }}"
roundcube_title: "{{ mail_server.split('.')[1] | capitalize }} Webmail"
roundcube_des_key: ''
roundcube_version: 1.6.1
roundcube_download_url: 'https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}-complete.tar.gz'
roundcube_db_username: roundcube
#roundcube_db_password : ''
roundcube_db_name: roundcube
#postgresql_root_password: ''
postgresql_version: 13

php_version: php7.4
php_fpm: '{{ php_version }}-fpm'

composer_version: 2.5.1

mail_server: 'mail.{{ default_domain }}'
sieve_port: 4190

ldap_scheme: ldapi
ldap_server: '%2Fvar%2Frun%2Fldapi'
ldap_port: 636
ldap_tls: true
ldap_suffix: "{{ 'dc={0},dc={1}'.format(*default_domain.split('.')) }}"
ldap_admin: "cn=admin,{{ ldap_suffix }}"
#ldap_pw: ''