backup_dir: "{{ playbook_dir }}/env/{{ env }}/backups"
reset_data: false

ldap_hostname: "{{ inventory_hostname }}"
ldap_ipv6: '{{ ipv6_address | default(false) }}'
ldap_localip: 127.0.0.2

ldap_domain: "{{ default_domain }}"
ldap_suffix: "{{ 'dc={0},dc={1}'.format(*ldap_domain.split('.')) }}"
ldap_scheme: ldapi
ldap_server: '%2Fvar%2Frun%2Fldapi'
ldap_log_level: 0x64 0x8

ldap_replication_enable: false
ldap_replication_user: "cn=replicator,{{ ldap_suffix }}"
#ldap_repliation_pw: ''
ldap_replication_hosts: []
ldap_replication_scheme: ldaps

ldap_rootdn: "cn=root,{{ ldap_suffix }}"
#ldap_rootpw: ''
ldap_admin: "cn=admin,{{ ldap_suffix }}"
#ldap_pw: ''

mail_domains:
  - "{{ default_domain }}"
mail_users: {}

# PPolicy Settings
ldap_ppolicy_enable: true
ppolicy_use_lockout: false
ppolicy_hash_cleartext: true
pwdExpireWarning: 0
pwdMaxFailure: 5
pwdSafeModify: 'FALSE'
pwdMinLength: 10
pwdCheckQuality: 2
pwdMaxAge: 0
pwdMinAge: 0
pwdLockoutDuration: 0
pwdAllowUserChange: 'TRUE'
pwdGraceAuthNLimit: 5
pwdInHistory: 5
pwdLockout: 'TRUE'
pwdFailureCountInterval: 0
pp_use_cracklib: 1
pp_min_points: 3
pp_min_upper: 1
pp_min_lower: 1
pp_min_digit: 1
pp_min_punct: 1
