firewall_enable: true

cert_scripts: [python3 /root/emby_cert.py example.local, python3 /root/unifi_cert.py example.local]

: false

pihole_https_enable: true

dashy_hostnames: 
  - 'dashy.example.local'
  - 'dashy.example2.local'
  - 'vm1.example.local'

dashy_name: 'EXAMPLE'
dashy_ipv6: 2001:db8:6666::76

kodi_hostname: '{{ inventory_hostname }}'
kodi_web_port: 8088
kodi_web_user: kodi
kodi_web_password: '{{ inventory_hostname_short }}'

kodi_user: pi

smb_workgroup: EXAMPLE

samba_hostnames: test4.example.local
samba_extra_domains: 
  - example2.local

samba_shares:
  downloads: 
    description: Downloads
    path: /home/admin/Downloads
    guest: yes
    force_user: admin
    directory_mask: '2770'
  private:
    description: Personal
    guest: no
    path: /home/admin/secrets
    writeable: 'no'

transmission_https: true
transmission_cert_name: seedbox.example.local
transmission_hostnames:
  - seedbox.example.local
  - torrents.example.local
  - seedbox.example2.local

transmission_allow_list:
  - 192.168.0.11
  - 192.168.0.13
  - 192.168.1.0/24

transmission_strict_hostnames: false
transmission_high_port: 65535
transmission_low_port: 49152
transmission_download_dir: /media/sf_Downloads
transmission_torrent_dir: '{{ transmission_download_dir }}/.torrents'
transmission_incomplete_dir: '{{ transmission_download_dir }}/.incomplete'


transmission_mounts:
  nas.example.local:
    - downloads

force_ipv4_mounts: true

unifi_network_domains:
  - example.local
  - example2.local