- name: Install apt https transport
  apt:
    name: [ca-certificates, apt-transport-https]
    state: latest

- name: Update unifi-video dependencies apt list
  template:
   dest: /etc/apt/sources.list.d/unifi-video.list
   src: unifi-video.list.j2

- name: Add mongodb gpg key
  apt_key:
    keyserver: https://www.mongodb.org/static/pgp/server-3.6.asc
    id: 58712A2291FA4AD5
    state: present

- name: Install openjdk-8
  apt:
   name: openjdk-8-jre-headless=8u252-b09-1~deb9u1
   state: present
   update_cache: yes

# Ubiquiti no longer supports Unifi-Video, so we need to install these manually.
- name: Ensure host has a copy of unifi-video and openjdk-8-jre-headless.
  copy:
    src: '{{ item }}'
    dest: '/var/cache/apt/archives/{{ item }}'
  with_items: 
    - libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
    - unifi-video3.10.13_amd64.deb

- name: Ensure openjdk and unifi-video are installed.
  apt:
    deb: '/var/cache/apt/archives/{{ item }}'
    state: present
  with_items: 
    - libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
    - unifi-video3.10.13_amd64.deb

- name: Ensure recordings folder has the correct permissions
  file:
    state: directory
    owner: unifi-video
    group: unifi-video
    path: '{{ videos_path }}'

- include: certs.yml
