# Set up certs for Unifi Apps
- set_fact: 
    unifi_domains: []

- set_fact: 
    unifi_domains: '{{ unifi_domains + ["*."+item.split(".")[-2:] | join(".")] }}'
  with_items: '{{ unifi_cert_domains }}'

- include_role:
    name: certbot_dns
  vars:
    cert_name: "{{ unifi_cert_name }}"
    cert_domains: '{{ unifi_domains }}'
  tags:
    - certbot

# Link Unifi certificates to locations Unifi OS expects.
- block:
  - name: Check if current certificate file is a link
    stat:
      path: /data/unifi-core/config/unifi-core.crt
    register: unifi_certificate_file
  - name: Remove existing certificate
    file:
      path: /data/unifi-core/config/unifi-core.crt
      state: absent
    when: not unifi_certificate_file.stat.islnk | default(True)
  - name: Link Let's Encrypt certificate file
    file:
      src: "/etc/letsencrypt/live/{{ unifi_cert_name }}/fullchain.pem"
      dest: /data/unifi-core/config/unifi-core.crt
      state: link
    when: not unifi_certificate_file.stat.islnk | default(True)
    notify: restart unifi-core
  - name: Check if current certificate key file is a link
    stat:
      path: /data/unifi-core/config/unifi-core.key
    register: unifi_certificate_key
  - name: Remove existing certificate key file
    file:
      path: /data/unifi-core/config/unifi-core.key
      state: absent
    when: not unifi_certificate_key.stat.islnk | default(True)
  - name: Link Let's Encrypt certificate key file
    file:
      src: "/etc/letsencrypt/live/{{ unifi_cert_name }}/privkey.pem"
      dest: /data/unifi-core/config/unifi-core.key
      state: link
    when: not unifi_certificate_key.stat.islnk | default(True)
    notify: restart unifi-core
 
- name: Update unifi certificate script.
  copy:
    src: unifi_cert.py
    dest: /root/unifi_cert.py
    mode: 0700

- name: Add deploy hook to certbot
  template:
    src: unifi.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/01-unifi.sh
    mode: 0770
    owner: root
    group: '{{ cert_group }}'

- name: Check for existing p12 certificate file.
  stat:
    path: /etc/letsencrypt/live/aceserv.network/fullchain.p12
  register: p12_cert_file

- name: Convert/import certificate using script.
  command: "python3 /root/unifi_cert.py {{ unifi_cert_name }}"
  when: not p12_cert_file.stat.exists | default(False)