- name: Ensure local certbot is up-to-date
  apt:
    name: python3-certbot-nginx
    state: latest
    install_recommends: yes
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Update the local certbot nginx configuration to accept certbot challenges
  template:
    src: nginx.conf.j2
    dest: '/etc/nginx/sites-available/cert.{{ cert_domain }}.conf'
  register: cert_config
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Ensure the local certbot nginx config is enabled
  file:
    src: '/etc/nginx/sites-available/cert.{{ cert_domain }}.conf'
    dest: '/etc/nginx/sites-enabled/cert.{{ cert_domain }}.conf'
    state: link
  register: cert_enable
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: 'Restart nginx on {{ local_cert_host }}'
  service:
    name: nginx
    state: restarted
  when: cert_enable.changed or cert_config.changed
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Check if key file exists.
  command:
    cmd: '/usr/bin/test -f /etc/letsencrypt/live/{{ cert_domain }}/privkey.pem'
  register: cert_key
  failed_when: false
  changed_when: cert_key.rc == 1
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- set_fact:
    deploy_hook: "{{ cert_services |  map('regex_replace', '(.+)', 'service \\1 restart') | join(';') }}"

# Used for cronjob time seed. 
- name: Get localhost name
  command:
    cmd: hostname
  register: hostname
  changed_when: False
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'
  run_once: True

- name: "Seed domain {{ cert_domain }}"
  block:
    - name: Run certbot
      shell:
        cmd: "/usr/bin/certbot certonly --webroot -n --agree-tos --email {{ cert_email }} -w /var/www/letsencrypt --cert-name {{ cert_domain }} -d {{ cert_domains | join(' -d ') }}"
  when: cert_key.changed or cert_config.changed
  throttle: 1
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Update cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: '/usr/bin/certbot renew --quiet --deploy-hook "{{ deploy_hook }}"'
    minute: "{{ (59 |random(seed=hostname.stdout)) }}"
    hour: "08"
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Ensure ssl-certs group can access the keys
  file:
    state: directory
    group: ssl-certs
    mode: 760
    path: "/etc/letsencrypt/live/{{ cert_domain }}"
    recurse: yes
  changed_when: false
  delegate_to: '{{ local_cert_host }}'
  vars:
    ansible_become_pass: '{{ local_sudo_password }}'
    ansible_ssh_user: '{{ local_cert_user }}'

- name: Ensure cert directory exists on remote host
  file:
    path: "/etc/letsencrypt/live/{{ cert_domain }}/"
    state: directory
    owner: root
    group: ssl-certs
    mode: 0760

- name: Ensure the remote host has a copy of the SSL Cert
  copy:
    src: "/etc/letsencrypt/live/{{ cert_domain }}/{{ item }}.pem"
    dest: "/etc/letsencrypt/live/{{ cert_domain }}/{{ item }}.pem"
  with_items:
    - fullchain
    - cert
    - privkey
    - chain
  register: new_certs