- name: Add all domains to a variable
  set_fact:
    cert_domains: "{{ [cert_domain] + cert_extra_domains | unique }}"

- name: Ensure we have a cert group
  group:
    name: '{{ cert_group }}'
    state: present

- include_tasks: provision.yml

- include_tasks: certbot.yml

