- name: Ensure backup folder exists
  local_action:
    module: file
    path: "{{ backup_dir }}/kodi/{{ inventory_hostname }}/"
    state: directory
  become: false

- name: Download copy of the databases.
  synchronize:
    src: /home/{{ kodi_user }}/.kodi/userdata/Database
    dest: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/'
    mode: pull
    
- name: Download a copy of the addons
  synchronize:
    src: /home/{{ kodi_user }}/.kodi/addons
    dest: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/'
    mode: pull

- name: Download a copy of the addon data
  synchronize:
    src: /home/{{ kodi_user }}/.kodi/userdata/addon_data
    dest: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/'
    mode: pull