- name: Check if backup folder exists.
  local_action:
    module: stat
    path: "{{ backup_dir }}/kodi/{{ inventory_hostname }}/"
  register: backup_dir_exists
  become: false

- block:
  - name: Stop Kodi
    command: 'kill -15 {{ kodi_pid }}'
    when: kodi_pid
  - name: Wait 15 seconds for Kodi to shutdown.
    wait_for:
      timeout: 15
    when: kodi_pid
  - name: Restore the databases.
    synchronize:
      dest: /home/{{ kodi_user }}/.kodi/userdata/
      src: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/Database'
      mode: push
    notify: restart kodi
  - name: Restore the addons
    synchronize:
      dest: /home/{{ kodi_user }}/.kodi/
      src: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/addons'
      mode: push
    notify: restart kodi
  - name: Restore the addon data
    synchronize:
      dest: /home/{{ kodi_user }}/.kodi/userdata/
      src: '{{ backup_dir }}/kodi/{{ inventory_hostname }}/addon_data'
      mode: push
    notify: restart kodi
  when: backup_dir_exists.stat.exists 