- include: certs.yml

- name: Check to ensure Emby data exists
  stat:
    path: /var/lib/emby
  register: emby_seeded
  changed_when: emby_seeded.stat.exists == false

# Handle install/upgrade process with .deb file
- block:
  - name: Check if Emby Server is installed
    command: apt list --installed emby-server
    register: emby_installed
    changed_when: emby_installed.stdout_lines | length < 2

  - set_fact:
      emby_server_installed_version: '{{ emby_installed.stdout | default("0.0.0.0") | regex_search("(\d\.\d.\d.\d)") }}'

  - name: Install Emby Server
    apt:
      deb: '{{ emby_server_deb_url }}'
    when: 
      - emby_server_version != emby_server_installed_version
      - emby_server_installed_version != '0.0.0.0'

# Ensure plugin backup folder exists.
- name: Ensure backup folder for "Server Configuration Backup" plugin exists.
  file:
    state: directory
    path: '{{ emby_server_backup_dir }}'
    owner: emby
  when: emby_server_plugin_backups

# Restore data when the folders didn't exist before the install.
- include: restore.yml
  when: emby_seeded.changed

- include: media.yml

- name: Update monit configuration file for Emby Server.
  template:
    src: monit.j2
    dest: /etc/monit/conf.d/emby
  notify: restart monit
  when: monit_enabled | default(true)