- name: "Create a list of shares for {{ item }}"
  set_fact:
    shares: "{{ smb_shares[item] | list }}"

- set_fact:
    share_prefix: "{{ item.split('.')[0] }}"
  when: not item | ipaddr 

- set_fact:
    share_prefix: "{{ item.split('.')[2] }}_{{ item.split('.')[3] }}"
  when: item | ipv4

- set_fact:
    share_prefix: "{{ item.split(':')[-1] }}"
  when: item | ipv6
    
- name: "Ensure network share folders exist for {{ item }}"
  file:
    state: directory
    path: "/media/{{ share_prefix }}_{{ share }}"
  register: new_network_shares
  loop: "{{ shares }}"
  loop_control:
    loop_var: share

- name: List newly created folders 
  set_fact:
    new_folders: '{% for path in new_network_shares.results if path.changed %}{{ path.path }} {% endfor %}'

# Used by Monit to detect when the mounts are disconnected.
- name: Ensure new folders have disconnected.txt file
  file:
    state: touch
    path: '{{ share_path }}/disconnected.txt'
  loop: "{{ new_folders.split(' ') }}"
  loop_control:
    loop_var: share_path
  when: new_folders != ''