- name: Ensure backup folder exists
  local_action:
    module: file
    path: "{{ backup_dir }}/emby/{{ inventory_hostname }}/"
    state: directory
  become: false

- name: Backup Emby data
  synchronize:
    dest: '{{ backup_dir }}/emby/{{ inventory_hostname }}/'
    src: '/var/lib/emby/{{ item }}'
    mode: pull
  with_items:
    - config
    - plugins
    - metadata
    - data
