- name: Ensure backup folder exists
  local_action:
    module: file
    path: "{{ backup_dir }}/emby/{{ inventory_hostname }}/"
    state: directory
  become: false

- name: Backup Emby data
  synchronize:
    dest: '{{ backup_dir }}/emby/{{ inventory_hostname }}/'
    src: '/var/lib/emby/{{ item }}'
    mode: pull
  with_items:
    - config
    - plugins
    - metadata
    - data

- block:
  - name: Ensure local plugin backup folder exists.
    local_action:
      module: file
      path: '{{ backup_dir }}/emby/{{ inventory_hostname }}/server_config_backup/'
      state: directory
    become: false
  - name: Grab a copy of the Server Configration Backup plugin backups.
    synchronize:
      dest: '{{ backup_dir }}/emby/{{ inventory_hostname }}/server_config_backup/'
      src: '{{ emby_backup_dir }}'
      mode: pull
  when: emby_plugin_backups