- name: Update network shares fstab file
  template:
    src: media.fstab.j2
    dest: /etc/fstab.media
  register: fstab_media

- name: Update network share credentials
  template:
    src: media.conf.j2
    dest: "/root/media.conf"
  register: media_cred

- name: Ensure cifs-utils is installed
  apt:
    name: cifs-utils
    state: present

# Config share mount folders
- include: mounts.yml
  with_items: '{{ emby_mounts }}'

- name: Add mount script
  template:
    src: fstab.if-up.j2
    dest: '/etc/network/if-up.d/fstab'
    mode: "0700"
    owner: root

- name: Remount drives
  command: /bin/mount -a -T /etc/fstab.media
  args:
    warn: no
  failed_when: False
  when: media_cred.changed or fstab_media.changed