- name: Set up virtualbox repo
  template:
    dest: /etc/apt/sources.list.d/virtualbox.list
    src: virtualbox.list.j2

- block:
  - name: Check if Visual Studio Code GPG Key exists
    stat:
      path: '/etc/apt/trusted.gpg.d/{{ item }}'
    register: gpg_key_files
    with_items:
      - 'oracle_vbox_2016.asc'
      - 'oracle_vbox.asc'

  - name: Import Visual Studio Code GPG Key
    get_url: 
      url: 'https://www.virtualbox.org/download/{{ item.item }}'
      dest: '/etc/apt/trusted.gpg.d/{{ item.item }}'
    with_items: '{{ gpg_key_files.results }}'
    when: not item.stat.exists

- name: Install VirtualBox
  apt:
    name: 'virtualbox-{{ vbox_version }}'
    state: latest
    update_cache: yes

- name: 'Ensure {{ vm_user }} is in the correct groups'
  user:
    append: yes
    groups: 
      - vboxusers
    name: "{{ vm_user }}"

# Added sleep so they don't all start at once
- name: Ensure cronjob exist for vms"
  cron:
    special_time: reboot
    name: "Start {{ item }}"
    job: "sleep {{ 60 + (count*30) }} && VBoxManage startvm '{{ item }}' --type headless"
    user: "{{ vm_user }}"
  with_items: '{{ vm_list }}'
  loop_control:
    index_var: count