- name: Install pre-reqs
  apt:
    name: [spamassassin, p7zip, amavisd-new, clamav, clamav-daemon, pyzor, razor, postfix-policyd-spf-python]
    state: present
  notify:
    - reload postfix

- name: Add system users to vmail group
  user:
    append: yes
    create_home: no
    groups: vmail
    name: "{{ item }}"
  with_items:
    - clamav
    - amavis

- name: Copy over spamassassin config file
  template:
    src: spamassassin/local.cf.j2
    dest: /etc/spamassassin/local.cf
  notify:
    - reload spamassassin

- name: Check if razor/pyzor are seeded.
  template:
    dest: /etc/mail/razor_pyzor
    src: spamassassin/razor_pyzor.j2
  register: seed_razor_pyzor

- name: Enable razor and pyzor
  command: "{{ item }}"
  with_items:
    - /usr/bin/razor-admin -create
    - razor-admin -register
    - pyzor discover
  become_user: amavis
  when: seed_razor_pyzor.changed
  
- name: Ensure spamassassin is running
  service:
    name: spamassassin
    state: started

- name: Ennsure spamassassin is enabled on boot
  service:
    name: spamassassin
    enabled: yes

- name: Ensure amavisd folders exist.
  file:
    state: directory
    owner: amavis
    group: vmail
    path: "{{ item }}"
  with_items:
    - /var/amavis/tmp
    - /var/amavis/infected

- name: Copy over amavisd config file
  template:
    src: "amavis/{{ item }}.j2"
    dest: "/etc/amavis/conf.d/{{ item }}"
  with_items:
    - 50-user
    - 15-content_filter_mode
  notify:
    - restart amavisd

- name: Copy over lists
  template:
    src: "amavis/{{ item }}.j2"
    dest: "/etc/amavis/{{ item }}"
  loop:
    - whitelist

- name: Create folders for amavis
  file:
    path: /var/spool/postfix/amavis
    state: directory
    owner: amavis
    group: vmail
    mode: 0750

- name: Add clamav user to vmail, amavis group
  user:
    append: yes
    create_home: no
    groups: vmail, amavis
    name: "clamav"

- name: Ensure Amavis/ClamAV is running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - clamav-freshclam
    - clamav-daemon
    - amavis
  
- name: Update SPF config
  template:
    src: amavisd/policyd-spf.conf.j2
    dest: /etc/postfix-policyd-spf-python/policyd-spf.conf
  notify: restart postfix

- name: Ensure ClamAV is enabled
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - clamav-freshclam
    - clamav-daemon
    - amavis

- include: dkim.yml