# Backup maildir
- name: Ensure local vamil backup folder exists.
  local_action:
    module: file
    state: directory
    path: '{{ backup_dir }}/mail/{{ mail_hostname }}/'
  become: false
  
- name: Take a snapshot of the vmail folder
  synchronize:
    dest: "{{ backup_dir }}/mail/{{ mail_hostname }}/"
    src: /var/vmail
    mode: pull
    copy_links: yes
    links: no
    delete: yes
    archive: yes
    recursive: yes

- name: Store a copy of the DKIM key/txt file.
  fetch:
    src: '/var/lib/rspamd/dkim/{{  item[0] }}_{{ item[1] }}.{{ item[2] }}'
    dest: '{{ backup_dir }}/dkim/{{ item[0] }}_{{ item[1] }}.{{ item[2] }}'
    flat: yes
  ignore_errors: true
  with_nested:
    - '{{ mail_domains }}'
    - '{{ dkim_keys }}'
    - [txt, private]

- name: Fecth a copy of the rspamd dynamic lists
  fetch:
    src: /var/lib/rspamd/{{ item }}
    dest: '{{ backup_dir }}/mail/{{ mail_hostname }}/{{ item }}'
    flat: yes
  with_items: '{{ rspamd_list_dbs }}'

- name: Backup redis database
  fetch:
    src: /var/lib/redis/dump.rdb
    dest: '{{ backup_dir }}/mail/{{ mail_hostname }}/redis.rdb'
    flat: yes
