- name: Enable contrib/non-free repo
  lineinfile:
    regex: '(deb http:\/\/deb\.debian\.org\/debian buslleye .+)'
    line: deb http://deb.debian.org/debian bullseye main contrib non-free
    path: /etc/apt/sources.list

- name: Install AMD drivers
  apt:
    state: present
    update_cache: yes
    name: [xserver-xorg-video-amdgpu, firmware-amd-graphics]
