- name: Enable contrib/non-free and non-free-firmware in repo
  lineinfile:
    regex: '(deb http://deb\.debian\.org/debian/ {{ debian_version }} main([\w\s-]*))'
    line: deb http://deb.debian.org/debian/ {{ debian_version }} main non-free contrib non-free-firmware
    path: /etc/apt/sources.list
    state: present

- name: Enable contrib/non-free deb-src in repo
  lineinfile:
    regex: '(deb-src http://deb\.debian\.org/debian/ {{ debian_version }} main([\w\s-]*))'
    line: deb-src http://deb.debian.org/debian/ {{ debian_version }} main non-free contrib non-free-firmware
    path: /etc/apt/sources.list
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install AMD drivers and related firmware
  apt:
    name: 
      - xserver-xorg-video-amdgpu
      - firmware-amd-graphics
    state: present

