- name: restart postfix
  service: 
    name: postfix 
    state: restarted

- name: reload postfix
  service: 
    name: postfix
    state: reloaded

- name: reload dovecot
  service:
    name: dovecot
    state: reloaded

- name: restart clamav-daemon
  service:
    name: clamav-daemon
    state: restarted

- name: restart clamav-freshclam
  service:
    name: clamav-freshclam
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted
  
- name: reload rspamd
  service:
    name: rspamd
    state: restarted

- name: restart rspamd
  service:
    name: rspamd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart monit
  service:
    name: monit
    state: restarted
  
- name: reload monit
  service:
    name: monit
    state: reloaded

