- name: Ensure wireguard is installed.
  apt:
    state: present
    name: wireguard
    
# Ensure server keys exist
- include: keys.yml

- include: psk.yml
  when: wg_psk

- name: Set sysctl variables
  sysctl:
    name: '{{ item }}'
    value: '1'
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/01-wireguard.conf
  with_items: 
    - '{{ wg_sysctl }}'

- name: Create list of IPv6 addresses required for WireGuard
  block:
  - set_fact: 
      wg_ipv6_addresses: []
  - set_fact:
      wg_ipv6_addresses: "{{ wg_ipv6_addresses + [wg_clients[item].ipv6|ipaddr('address')] }}"
    with_items: '{{ wg_clients }}'
  when: wg_ipv6_subnet

- name: Check wg configuration
  template:
    dest: /etc/wireguard/wg0.test
    src: wg0.conf.j2
    mode: '0600'
  register: wg_settings

- block: 
  - name: Stop WireGuard
    command: wg-quick down wg0
    ignore_errors: yes
  - name: Update WireGuard configuration
    template:
      dest: /etc/wireguard/wg0.conf
      src: wg0.conf.j2
      mode: '0600'
  - name: Start WireGuard
    command: wg-quick up wg0
  when: wg_settings.changed

- name: Ensure WireGuard server is enabled
  service:
    name: wg-quick@wg0
    enabled: yes

- include: backups.yml

- name: Updated WireGuard monit configuration
  template:
    src: monit.j2
    dest: /etc/monit/conf.d/wireguard
  notify: restart monit
  when: monit_enabled | default(true)
