nameservers:
  ns1:
    ipv4: 172.16.1.1
    ipv6: 2001:db8:40::1111
    domain: example.local
  ns2:
    name: ns2
    ipv4: 172.16.2.2
    ipv6: 2001:db8:50::2222
    domain: example.local

dns_zones:
  # example.local
  example.local:
    mail: mail.example.local
    backup_mail:
      - mail.example2.local
    dnssec: true
    hostnames:
      '@':
        ipv4: 172.16.1.2
        ipv6: 2001:db8:40::aaaa
      ip:
        ipv4: 172.16.1.2
        ipv6: 2001:db8:40::222
      ipv4:
        ipv4: 172.16.1.2
      ipv6: 
        ipv6: 2001:db8:40::222
      mail:
        ipv4: 172.16.1.3
        ipv6: 2001:db8:40::10
      rspamd:
        ipv4: 172.16.1.3
        ipv6: 2001:db8:40::11
      ldap:
        ipv4: 172.16.1.3
        ipv6: 2001:db8:40::12
      cloud1:
        ipv4: 172.16.1.3
        ipv6: 2001:db8:40::e6d8
      cloud2:
        ipv4: 172.16.2.3
        ipv6: 2001:db8:50::e6b4
      webmail:
        ipv4: 172.16.1.3
        ipv6: 2001:db8:40::c
    cnames:
      autoconfig: 'mail.example.local'
      autodiscover: 'mail.example.local'
  # example2.local
  example2.local:
    mail: mail.example.local
    backup_mail:
      - mail.example2.local
    dnssec: true
    hostnames: 
      '@':
        ipv4: 172.16.2.2
        ipv6: 2001:db8:50::ac
      ip:
        ipv4: 172.16.2.2
        ipv6: 2001:db8:50::196
      ipv4:
        ipv4: 172.16.2.2
      ipv6: 
        ipv6: 2001:db8:50::196
      mail:
        ipv4: 172.16.2.3
        ipv6: 2001:db8:50::2
      ldap:
        ipv4: 172.16.2.3
        ipv6: 2001:db8:50::b
      rspamd:
        ipv4: 172.16.2.3
        ipv6: 2001:db8:50::4e
      autoconfig: 'mail.example.local'
      autodiscover: 'mail.example.local'
 