nameservers:
  ns1:
    ipv4: 192.168.0.2
    ipv6: 2001:db8:1234::2
    domain: example.local
  ns2:
    ipv4: 192.168.0.3
    ipv6: 2001:db8:4321::2
    domain: example.local

dns_zones:
  # example.local
  example.local:
    mail: mail.example.local
    backup_mail:
      - mail.example2.local
    dnssec: false
    spf_txt: 'v=spf1 a mx ~all'
    dmarc_txt: 'v=DMARC1;p=reject;adkim=s;aspf=s;fo=1;rf=afrf;rua=mailto:dmarc@example.local'
    hostnames:
      '@':
        ipv4: 192.168.0.2
        ipv6: 2001:db8:4321::1
      ip:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::1122
      ipv4:
        ipv4: 192.168.0.2
      ipv6: 
        ipv6: 2001:db8:1234::1122
      mail:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::3
      rspamd:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::4
      ldap:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::5
      cloud1:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::1
      cloud2:
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::1
      vm1:
        ipv4: 192.168.0.4
      vm2:
        ipv4: 192.168.0.5
      webmail:
        ipv4: 192.168.0.2
        ipv6: 2001:db8:1234::6
      files:
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::6
    cnames:
      autoconfig: 'mail.example.local'
      autodiscover: 'mail.example.local'
  # example2.local
  example2.local:
    mail: mail.example.local
    backup_mail:
      - mail.example2.local
    dnssec: true
    hostnames: 
      '@':
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::1
      mail:
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::3
      ldap:
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::5
      rspamd:
        ipv4: 192.168.0.3
        ipv6: 2001:db8:4321::4
      emby:
        ipv6: 2001:db8:abcd::eb
        ipv4: 192.168.0.4
      autoconfig: 'mail.example.local'
      autodiscover: 'mail.example.local'
 