dkim_key: 'example'
dkim_keys: 
  - '202201'
  - '{{ dkim_key }}'

mail_domains:
  - example.local
  - example2.local

spam_milter: 'rspamd'

spammed_accounts:
  - spotify@example.local
  - invoices@example.local

rejected_addresses:
  - email: no-reply@example.local
    code: '550'
    msg: "No replies, it's in the address..."

spam_domain_scoring:
   us: 4.0
   pro: 5.0
   cam: 8.0
   us: 1.0
   webcam: 8.5