# This file should be encrypted using ansible-vault (https://docs.ansible.com/ansible/latest/user_guide/vault.html).

# User accounts automatically added to any Linux/Unix host.
users:
  admin:
    name: admin
    password: "BlueFlexibilitiesSmokeOutdoors"
  ansible:
    name: ansible
    password: "Example_123{{ inventory_hostname_short[:2] }}321_Example"

# Users added to the samba share when using the samba role.
samba_users:
  admin:
    name: admin
    password: "{{ users.admin.password }}"
  media:
    name: media
    password: "Abc123"
