# This file should be encrypted with ansible-vault.
users:
  admin:
    password: "Abcd1234!"
  guest:
    password: "AbCd.{{ inventory_hostname_short[:4] }}!1234"

samba_users:
  admin:
    password: "{{ users.admin.password }}"
  guest:
    password: "guest"
  media:
    password: "{{ media_password }}"

dashy_users:
  admin:
    password: "d4shy."
  guest:
    password: "guest"

postgresql_root_password: 'AbCdE.132465!'
roundcube_db_password: "AbCDe-{{ inventory_hostname_short[:4] }}5367."

ldap_rootdn: "cn=root,{{ ldap_suffix }}"
ldap_rootpw: "R00tdn,54321"
ldap_admin: "cn=admin,{{ ldap_suffix }}"
ldap_pw: "qRsTUV.{{ env[:2] }}-09876"
ldap_replication_user: "cn=replication,{{ ldap_suffix }}"
ldap_replication_pw: "hIJKl<123456."

rspamd_controller_password: 'Let me in.'

doveadm_password: 'Fake Dove Admin Password'

dqs_key: 1a1a1a1a1a1a1a1a1a1a1a1a1a1

media_user: media
media_password: Med1a P4ssword.

smb_user: media
smb_password: Med1a P4assword.

nordvpn_user: norduser@nordvpn.com
nordvpn_password: VPN Password!

#You will likely have to dict this one tool
backblaze_app_keys:
  cloud1:
    app_id: '0000000000000000000000000'
    app_key: 0123456789abcdefghijklmnopqrstu

blackblaze_ssec_keys:
  email:
    key_b64: QW4gZXhhbXBsZSBiYXNlNjQga2V5LiBQbGVhc2UgY2hhbmdlIGl0IQo=
    key_id: ABCDEFGHabcdefgh0123456789
