# This file should be encrypted with ansible-vault.

users:
  admin:
    password: "Nonetheless Alive Free!"
  ansible:
    password: "Idempotent {{ inventory_hostname_short[:6] }} magic."

postgresql_root_password: 'spring3yogurtlast20tree771322steam'
roundcube_db_password: "250stoodrope192692balleitherbut"

ldap_rootdn: "cn=root,{{ ldap_suffix }}"
ldap_rootpw: "plural40miss0each92ninecard9712"
ldap_admin: 'cn=admin,{{ ldap_suffix }}'
ldap_pw: "would51cowlife768379yeardescribe19"
ldap_replication_user: "cn=reptar,{{ ldap_suffix }}"
ldap_replication_pw: "23landat9end44nextother7255"

rspamd_controller_password: Spam in a can.

doveadm_password: Rain_or_shine_1234


