ansible_connection: ssh
ansible_ssh_user: admin
ansible_become_password: "{{ users.ansible.password }}"
ansible_python_interpreter: /usr/bin/python3
env: "example"

timezone: America/Toronto
sshd_keytype: ed25519

primary_user: admin
sudo_users:
  - admin

backup_dir: "{{ playbook_dir }}/env/{{ env }}/backups"

trusted_hosts:
  - "{{ local_ip }}"
  - 2001:db8::/32

# LDAP
ldap_domain: "{{ ansible_fqdn.split('.', 1)[1] }}"
ldap_suffix: "{{ 'dc={0},dc={1}'.format(*ldap_domain.split('.')) }}"
ldap_admin: 'cn=admin,{{ ldap_suffix }}'

# Mail
default_domain: example.local
mail_hostname: "mail.{{ default_domain }}"
webmail_hostname: "webmail.{{ default_domain }}"
cert_email: certs@example.local
php_fpm: php8.2-fpm
doveadm_port: 12345

# Network
local_ip: 10.0.1.2
local_ipv6: '2001:db8:abcd:222::/64'
local_subnet: 192.168.0.0/24

local_subnets: ['{{ local_subnet }}', '{{ local_ipv6 }}']