- set_fact:
    pihole_cert_domains: '{{ "*."+pihole_hostname.split(".")[-2:] | join(".") }}'
  when: pihole_cert_domains == []
  
- include_role:
    name: certbot_dns
  vars:
    cert_name: "{{ pihole_cert_name }}"
    cert_domains: '{{ pihole_cert_domains }}'
    cert_ipv6: '{{ pihole_ipv6 }}'
  tags:
    - certbot