backblaze_backups: []
backblaze_ssec_keys: {}
backblaze_app_keys: {}
backblaze_app_id: '{{ inventory_hostname_short }}'
backblaze_venv: /usr/backblaze
backblaze_config_dir: /root
backblaze_default_keepdays: 30

backblaze_default_hour: '04'